name: Simple Test Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: コードを取得
        uses: actions/checkout@v4

      - name: hello.txt に Hello という文字があるかテスト
        run: grep "Hello" hello.txt
